CREATE TABLE PRODUTOFORNECEDOR
(
	IDPRODUTO INT NOT NULL,
    IDFORNECEDOR INT NOT NULL,
	PRIMARY KEY (IDPRODUTO, IDFORNECEDOR),
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO),
	FOREIGN KEY (IDFORNECEDOR) REFERENCES FORNECEDOR (IDFORNECEDOR)
)