/*DELIMITER $
	CREATE FUNCTION MENSAGEM() RETURNS CHAR(40) SEMPRE RETORNA UM VALOR
		BEGIN
			RETURN "HELLO WORLD";
		END
        $*/
        
/*SELECT MENSAGEM();*/

/*DELIMITER $
	CREATE FUNCTION SITUACAO(MEDIA FLOAT) RETURNS CHAR(40)
		BEGIN   
			IF MEDIA < 5 THEN
				RETURN "REPROVADO";
			ELSE 
				IF MEDIA < 7 THEN
					RETURN "RECUPERAÇÃO";
				ELSE 
					RETURN "APROVADO";
				END IF;
			END IF;
		END;
        $*/

/*SELECT NOTA1,
	     NOTA2,
	     NOTA3,
		 (NOTA1 + NOTA2 + NOTA3)/3 AS MEDIA,
         SITUACAO((NOTA1 + NOTA2 + NOTA3)/3)
	FROM NOTA*/

/*DELIMITER $
	CREATE FUNCTION NOVA_MEDIA(MEDIA FLOAT) RETURNS FLOAT
		BEGIN
			IF (MEDIA >= 5) AND (MEDIA <= 7) THEN
				RETURN MEDIA + 0.5;
			ELSE 
				IF (MEDIA > 7) AND (MEDIA >= 9) THEN
					RETURN MEDIA + 0.7;
				ELSE 
					IF (MEDIA > 9) THEN
						RETURN MEDIA + 0.8;
					ELSE 
						RETURN MEDIA;
					END IF;
				END IF;
			END IF;
		END $*/

/*SELECT NOTA1,
	   NOTA2,
	   NOTA3,
	ROUND ((NOTA1 + NOTA2 + NOTA3)/3,1) AS MEDIA,
	   SITUACAO((NOTA1 + NOTA2 + NOTA3)/3) AS SITUACAO,
	ROUND (NOVA_MEDIA((NOTA1 + NOTA2 + NOTA3)/3),1) AS NOVA_MEDIA
FROM NOTA*/

			

                    