/*
DELIMITER $$
	CREATE PROCEDURE AUMENTA_NOTA(IN PONTO INTEGER)
    BEGIN
		IF PONTO = 1 THEN
			UPDATE NOTA
				SET NOTA1 = NOTA1 +1;
		ELSE
			IF PONTO = 2  THEN
				UPDATE NOTA
					SET NOTA2 = NOTA2 + 1;
        ELSE        
			IF PONTO = 3 THEN
				UPDATE NOTA
					SET NOTA3 = NOTA3 + 1;
			END IF;
			END IF;
		END IF;
	END $$;
DELIMITER $$;
*/

/*SELECT * FROM NOTA*/

/*CALL AUMENTA_NOTA (1);*/

/*DELIMITER $$
	CREATE PROCEDURE DELETA_NOTA()
    BEGIN
		DELETE FROM NOTA
			WHERE NOTA1 > 10
				OR NOTA2 > 10
                OR NOTA3 > 10;
	END $$;
DELIMITER $$;*/