/*CREATE DATABASE BANCO1710;

USE BANCO1710;

CREATE TABLE Produtos
(
    Referencia  VARCHAR(3) PRIMARY KEY,
    Descricao   VARCHAR(50) UNIQUE,
    Estoque INT NOT NULL DEFAULT 0
);
 
INSERT INTO Produtos VALUES ('001', 'Feijão', 10);
INSERT INTO Produtos VALUES ('002', 'Arroz', 5);
INSERT INTO Produtos VALUES ('003', 'Farinha', 15);
 
CREATE TABLE ItensVenda
(   
    Venda       INT,
    Produto VARCHAR(3),
    Quantidade  INT
);*/

/*DELIMITER $
	CREATE TRIGGER TRG_IV_AFT_INS AFTER INSERT 
    ON ITENSVENDA
		FOR EACH ROW 
			BEGIN
				UPDATE PRODUTOS 
                SET ESTOQUE = ESTOQUE - NEW.QUANTIDADE
                WHERE REFERENCIA = NEW.PRODUTO;
			END$*/
            
/*INSERT INTO ITENSVENDA
VALUES (1, '001', 3);*/

/*SELECT *
FROM PRODUTOS*/
            
/*INSERT INTO ITENSVENDA
VALUES (2, '002', 1)*/

/*SELECT *
FROM PRODUTOS*/

/*DELIMITER $
	CREATE TRIGGER TGR_IV_AFT_DEL AFTER DELETE
    ON ITENSVENDA 
		FOR EACH ROW 
			BEGIN
				UPDATE PRODUTOS
                SET ESTOQUE = ESTOQUE + OLD.QUANTIDADE 
				WHERE REFERENCIA = OLD.PRODUTO;
            END$*/
            
/*DELETE FROM ITENSVENDA
WHERE VENDA = 1
	AND PRODUTO = '001';*/
    
/*SELECT *
FROM PRODUTOS*/